[project]
name = "metbrowser"
version = "0.1.0"
description = "Met Museum Browser for macOS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pyside6>=6.5.3,<6.6", 
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]

