name: Build macOS App

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
          pip install loguru pyside6 requests tqdm

      - name: Build app
        run: python setup.py py2app

      - name: Ad-hoc sign the app
        run: |
          codesign --force --deep --sign - "dist/Met Browser.app"

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Met Browser" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 425 120 \
            "Met-Browser.dmg" \
            "dist/Met Browser.app" || true

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Met-Browser-App
          path: dist/Met Browser.app
          retention-days: 30

      - name: Upload DMG (if created)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Met-Browser-DMG
          path: "*.dmg"
          retention-days: 30
