name: Build macOS App

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
          pip install loguru pyside6 requests tqdm

      - name: Build app (alias mode for testing)
        run: python setup.py py2app -A

      - name: Fix permissions
        run: chmod -R 755 "dist/Met Browser.app"

      - name: Ad-hoc sign everything
        run: |
          find "dist/Met Browser.app" -type f \( -name "*.so" -or -name "*.dylib" \) -exec codesign --force --sign - {} \;
          codesign --force --deep --sign - "dist/Met Browser.app"

      - name: Verify signature
        run: codesign --verify --verbose "dist/Met Browser.app" || true

      - name: Zip the app
        run: |
          cd dist
          zip -r "../Met-Browser.zip" "Met Browser.app"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: Met-Browser-macOS
          path: Met-Browser.zip
          retention-days: 30
